# Generated by Django 5.1.1 on 2024-09-18 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="название")),
                ("model", models.CharField(max_length=150, verbose_name="модель")),
                (
                    "create_data",
                    models.DateField(verbose_name="дата выхода продукта на рынок"),
                ),
            ],
            options={
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
            },
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="название")),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=150,
                        null=True,
                        unique=True,
                        verbose_name="почта",
                    ),
                ),
                ("country", models.CharField(max_length=50, verbose_name="страна")),
                ("city", models.CharField(max_length=50, verbose_name="город")),
                (
                    "street",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="улица"
                    ),
                ),
                (
                    "house",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="номер дома"
                    ),
                ),
                (
                    "debt",
                    models.FloatField(
                        blank=True,
                        default=0.0,
                        null=True,
                        verbose_name="задолженность перед поставщиком",
                    ),
                ),
                (
                    "create_data",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="время создания"
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="network.link",
                        verbose_name="поставщик",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        default=None, to="network.product", verbose_name="продукты"
                    ),
                ),
            ],
            options={
                "verbose_name": "звено",
                "verbose_name_plural": "звенья",
            },
        ),
    ]
